spring:
  security:
    oauth2:
      client:
        registration:
          aws:
            client-id: 305cgjh7bp73nvpie08uhdrn7k
            client-secret: bj892m9outgnl3kdig8u3bmjdfvvfblqjfuj0phk8an5ho6ao9f
  webflux:
    hiddenmethod:
      filter:
        enabled: true

